core.symlinks=false
core.autocrlf=true
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
diff.astextplain.textconv=astextplain
rebase.autosquash=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
credential.helper=!"C:/Anaconda3/envs/SmartQ/Library/mingw64/libexec/git-core/git-credential-store.exe"
user.name='minguencho'
user.email=cho000130@naver.com
user.password='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'
credential.helper=store
core.editor=C:\Users\mgcho\AppData\Local\Programs\Microsoft VS Code\Code.exe --wait
credential.helperselector.selected=store
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/BangMingGing/SmartQ4Deploy.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main
remote.mgcho.url=https://github.com/minguencho/SmartQ4Depoly.git
remote.mgcho.fetch=+refs/heads/*:refs/remotes/mgcho/*
